### ISSUE TITLE
Allow use of environment variables in settings

### ISSUE THREAD

**Issue by davist11** [shennyg/azure-blob-remote-volume#3]
It would be awesome if we could use environment variables in the additional settings:

* Account Name
* Account Key
* Container Name
* Subfolder

Looks like you would need to use `parseEnv()` on those values: https://docs.craftcms.com/v3/extend/environmental-settings.html

Let me know if you'd like me to enter a PR

**Comment by shennyg** [comment]
PR would be great, I'd love to see it upgraded to a autosuggestField field and adding `autosuggestField: true`, see: [Autosuggest Inputs](https://docs.craftcms.com/v3/extend/environmental-settings.html#validation).

**Comment by davist11** [comment]
You got it: #4

**Comment by davist11** [comment]
Can you also push a new release?

**Comment by shennyg** [comment]
@davist11 I didn't realize you didn't tag it. I tagged and pushed: https://packagist.org/packages/shennyg/azure-blob-remote-volume#1.0.2 

Thanks so much for your contribution!
